version: 2
updates:
  - package-ecosystem: "" # See documentation for possible values
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
